from app.models.models import (
    AiCallUsage,
    Appointment,
    CallLog,
    Campaign,
    CampaignNumber,
    Debt,
    Extension,
    InboundRoute,
    License,
    PaymentPromise,
    Queue,
    SystemSettings,
    Tenant,
    Trunk,
    User,
    VoiceBot,
)

__all__ = [
    "AiCallUsage",
    "Appointment",
    "CallLog",
    "Campaign",
    "CampaignNumber",
    "Debt",
    "Extension",
    "InboundRoute",
    "License",
    "PaymentPromise",
    "Queue",
    "SystemSettings",
    "Tenant",
    "Trunk",
    "User",
    "VoiceBot",
]
